<?php
// create a class that performs routing

class Router {

  // lists of routes, implicitly white-listed.
  $routes = array();

  // look at request url (e.g. https://oursite/customer-order/)

  // break url into tokens. determine if request is GET or POST

  // decipher route from tokens using a whitelist of available routes

  // perform action. possibly by handing parameters over to some other class

}

?>
