<?php
$template = <<<EOT
<h2>SUP</h2>

<p>
SUP (the student university page), is a unified discovery layer, aimed
to help students organize, and come together for the causes they are
passionate about.
</p>

<h2>Join an RSO</h2>

<p>
Using SUP, joining a registered student organization is easier than ever.
Simply register using your e-mail, and request to join RSO's
</p>

<h2>Attend Events</h2>

<p>
Discover events that are being hosted on your campus, and find out how
you can participate. Using SUP, it is possible to create your own
RSO's and your own events.
</p>

EOT;
?>
