<?php

$template = <<<EOT
<div id="inner-content">
<h3>Help Page</h3>

<h4>Make an Account</h4>
<p>
To make an account, click the 'new account' button in the top right. Be sure to include the university
you attend, and provide an e-mail belonging to that university.
</p>

<h4>Start an RSO</h4>
<p>
To create an RSO, go to your account page and click the "Create RSO" link. Be sure to provide the user names of
at least 5 students from your university. You will be chosen as the RSO's administrator by default; 
You may, optionally, choose one student as an administrator to the RSO.
</p>

<h4>Create an Event</h4>
<p>
From your account page, click the 'Create Event' link. Once you are in the form, be sure to populate all the
required fields. To ensure your event is activated immediately, indicate that it is created by an RSO that
you administrate. If no RSO is specified, the event will be made pending until it is approved by the
{{¡¡¡SUPER ADMINISTRATOR!!!}}.
</p>

</div>
EOT;

?>
